### ISSUE TITLE
Mongo username/password not required in Mule Studio

### ISSUE THREAD

**Issue by ryan1234** [mulesoft/mongo-connector#18]
I was using Mule Studio 3.2 and when using the Mongo cloud connector, the username and password were required fields.  Even though I didn't need them, I put them in so I could make calls.

Mule Studio 3.3 has a slightly newer version of the Mongo cloud connector and username and password are now not required.  When left out queries with Mongo do not work.  An error is thrown instead.

I would recommend making them required or throwing a more meaningful error.

**Comment by cmartinezledo** [comment]
It's true Ryan, but with the migration to a new DevKit version, this will not happen again. You can see the migration status right [here](https://www.mulesoft.org/jira/browse/CLDCONNECT-2361)
