### ISSUE TITLE
find-one-object-using-query-map calls reconnection strategy when item not found

### ISSUE THREAD

**Issue by Fydon** [mulesoft/mongo-connector#19]
I've setup a default reconnection strategy for connectors, but because find-one-object-using-query-map throws an exception when it fails to find the object being queried, the query retries according to the reconnection strategy, but why does this connector throw an exception, when the MongoDB Java Driver would return null, which we could then test for and perform the correct action?

As a work around I now use count-objects-using-query-map to check if the item exists before using find-one-object-using-query-map to find the object, but that requires an extra check, when I could use find-one-object-using-query-map to check if the item exist and return the object.

I'm using the latest version of the mongo-connector stored on the Mule repository 3.0.0.201212071410.

**Comment by cmartinezledo** [comment]
Closing as solution was provided in previous comments
