### ISSUE TITLE
How to use query-ref in update-objects is not clear

### ISSUE THREAD

**Issue by gmsharpe** [mulesoft/mongo-connector#21]
I'm trying to use the following query-ref:

query-ref="#[string : { 'iamid' : #[message.outboundProperties['iamid']]}]"

I'm not exactly sure why we need to use #[ string : .... 

Any help deciphering the problem appreciated.  Would also greatly appreciate some more examples of using the various mongo operations included with the connector. 

The error I get is:

Message               : Failed to invoke updateObjects. Message payload is of type: BasicDBObject
Code                  : MULE_ERROR--2
--------------------------------------------------------------------------------
Exception stack is:
1. [Error: could not access: string; in class: null]
[Near : {... Unknown ....}]
             ^
[Line: 1, Column: 0] (org.mvel2.PropertyAccessException)
  org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer:611 (null)
2. Execution of the expression "string : { 'iamid' : #[message.outboundProperties['iamid']]}" failed. (org.mule.api.expression.ExpressionRuntimeException)
  org.mule.el.mvel.MVELExpressionLanguage:208 (http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/expression/ExpressionRuntimeException.html)
3. Failed to invoke updateObjects. Message payload is of type: BasicDBObject (org.mule.api.MessagingException)
  org.mule.module.mongo.processors.UpdateObjectsMessageProcessor:189 (http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/MessagingException.html)
--------------------------------------------------------------------------------
Root Exception stack trace:
[Error: could not access: string; in class: null]
[Near : {... Unknown ....}]
             ^
[Line: 1, Column: 0]
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.getBeanProperty(ReflectiveAccessorOptimizer.java:611)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.getBeanPropertyAO(ReflectiveAccessorOptimizer.java:439)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.compileGetChain(ReflectiveAccessorOptimizer.java:353)
    + 3 more (set debug level logging or '-Dmule.verbose.exceptions=true' for everything)

**Comment by cmartinezledo** [comment]
Closing as solution was provided in previous comments
