### ISSUE TITLE
For Each 

### ISSUE THREAD

**Issue by samek** [mulesoft/mongo-connector#27]
How would one: 
Fetch data from mongo, put it into foreach and query mongo again, then have this data available not from the first connection ? 

For example data *which in log is logged BEFORE FOR EACH / OUTPUT*  get's into the For Each, where i query different Collection with hostname, after the foreach is done the payload is still like it was before for each. 

How do you guys solve that problem ? 

Thanks. 

----------------
INFO  2013-06-28 10:12:21,478 [[mongo].connector.http.mule.default.receiver.02] org.mule.api.processor.LoggerMessageProcessor: INSIDE FOR EACH:   [ { "_id" : { "$oid" : "4f3d190058b72e3afc000000"} , "status" : "DONE" , "type" : "clip"}]
INFO  2013-06-28 10:12:21,491 [[mongo].connector.http.mule.default.receiver.02] org.mule.api.processor.LoggerMessageProcessor: INSIDE FOR EACH:   [ { "_id" : { "$oid" : "4f3d31d8192576fe42000000"} , "status" : "DONE" , "type" : "clip"}]
INFO  2013-06-28 10:12:21,518 [[mongo].connector.http.mule.default.receiver.02] org.mule.api.processor.LoggerMessageProcessor: INSIDE FOR EACH:   [ { "_id" : { "$oid" : "4f61e3ffda92bde131000000"} , "status" : "DONE" , "type" : "clip"}]
INFO  2013-06-28 10:12:21,552 [[mongo].connector.http.mule.default.receiver.02] org.mule.api.processor.LoggerMessageProcessor: INSIDE FOR EACH:   [ { "_id" : { "$oid" : "4f7060479b00050473000000"} , "status" : "DONE" , "type" : "clip"}]
INFO  2013-06-28 10:12:21,559 [[mongo].connector.http.mule.default.receiver.02] org.mule.api.processor.LoggerMessageProcessor: BEFORE FOR EACH / OUTPUT [ { "_id" : { "$oid" : "4f3cf85cca99ebaab2a7a152"} , "hostname" : "qt_mini1.isis.internal" , "ip" : "192.168.23.36" , "date" : 1372407122} , { "_id" : { "$oid" : "4f3d2e8aca99ebaab2a7a153"} , "hostname" : "qt_mini2.isis.internal" , "ip" : "192.168.23.39" , "date" : 1372407122} , { "_id" : { "$oid" : "4f61ec5f0ca5511bbdd15a6b"} , "hostname" : "qt_mini3.isis.internal" , "ip" : "192.168.23.38" , "date" : 1372407122} , { "_id" : { "$oid" : "4f7451920ca5511bbdd15a6c"} , "hostname" : "qt_mini4.isis.internal" , "ip" : "192.168.23.37" , "date" : 1372407122}]

**Comment by cmartinezledo** [comment]
Closing as solution was provided in previous comments
