### ISSUE TITLE
findObjects methods do not support sort

### ISSUE THREAD

**Issue by cfedersp** [mulesoft/mongo-connector#35]
Issue:
findObjects does not expose sorting the cursor. 

Suggested Solution:
Two parameters must be added to specify the sort field and ascending/descending order. Ex: sortField="fieldName" and sortAscending="true" and MongoClientImpl must sort the cursor if sortField attribute is not null.

I have this fixed and tested locally, so if you add me as a contributor and tell me which branch to use, I can commit my change.

**Comment by cmartinezledo** [comment]
Issue has been fixed.
