### ISSUE TITLE
Aggregation Methods not supported

### ISSUE THREAD

**Issue by cfedersp** [mulesoft/mongo-connector#36]
MongoDB has a powerful aggregation features that should be exposed to Mule users. 
Here is a draft list of 10 meaningful @Processors to expose by implementing combinations of MongoDB's Aggregation operators:

1) Group -min
2) Group -max
3) Group -sum
4) Group -average
5) Sort
6) Sort -Group-first
7) Sort -Group-last
8) GeoNear
9) Project
10) Project -unwind

The remaining operators, "match", "skip" and "limit" apply to all the above major operators and merely limit the domain the aggregators operate over.

Group Usage example:
Given a hypothetical collection of issues raised by users, 
To count the number of different types of issues submitted by user "1", without knowing the different values for the various issueTypes ahead of time:
db.issues.aggregate(
	{$match: {"userId" : "1"}}, 
	{$group : {_id : { userId:'$userId', issueType : '$issueType' },
		issuesFromUser : { $sum : 1 }
	}});
Returns a result containing the userId, the issueType and the total number of rows that link that issueType to that user.

**Comment by cmartinezledo** [comment]
There is a Jira ticket created about this issue in order to implement this missing features.

You can follow this issue status here:  [Jira](https://www.mulesoft.org/jira/browse/CLDCONNECT-2323)
