### ISSUE TITLE
connection string of mongodb replicaset

### ISSUE THREAD

**Issue by kalinchih** [mulesoft/mongo-connector#43]
Hi,

How to set the mule mongo connector for a mongodb replicaset?

For example, host1:8001,host2:8001/?replicaSet=mySet&readPreference=secondary

I have tried to put the above string in Host and leave port empty, but failed.

many thanks,

kalin

**Comment by birkand** [comment]
Hi,

I have a mongodb replicaset with multiple ports from a service provider,

 i.e. host1:9876,host2:10987

but could not find a way to configure the connector with this requirement.

Thanks.

Birkan

**Comment by cmartinezledo** [comment]
Actually MongoDB Connector supports multi-host (The host field must be a list of comma separated hosts) But it does not support multi-port.

An issue has been opened, you can track it from [here](https://www.mulesoft.org/jira/browse/CLDCONNECT-2364)
