### ISSUE TITLE
MongoClientImpl.java throws a ClassCastException when you try to insert an object with an "_id" that is not an ObjectId

### ISSUE THREAD

**Issue by gmsharpe** [mulesoft/mongo-connector#44]
Mongo does not require that the "_id" equal a ObjectId.  In fact, they even recommend defining the _id field explicitly in some scenarios (see http://docs.mongodb.org/manual/faq/developers/#how-do-i-optimize-storage-use-for-small-documents).

The MongoClientImpl throws a ClassCastException, though, if the _id is present and not cast-able to an ObjectId.  I'm not clear whether this actually prevents the object from being inserted, but the error message does state that it "Failed to invoke insertObject"

<code>
*******************************************************************************
Message               : Failed to invoke insertObject. Message payload is of type: BasicDBObject
Code                  : MULE_ERROR--2
--------------------------------------------------------------------------------
Exception stack is:
1. java.lang.String cannot be cast to org.bson.types.ObjectId (java.lang.ClassCastException)
  org.mule.module.mongo.api.MongoClientImpl:176 (null)
2. Failed to invoke insertObject. Message payload is of type: BasicDBObject (org.mule.api.MessagingException)
  org.mule.devkit.processor.DevkitBasedMessageProcessor:128 (http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/MessagingException.html)
--------------------------------------------------------------------------------
Root Exception stack trace:
java.lang.ClassCastException: java.lang.String cannot be cast to org.bson.types.ObjectId
	at org.mule.module.mongo.api.MongoClientImpl.insertObject(MongoClientImpl.java:176)
	at org.mule.module.mongo.MongoCloudConnector.insertObject(MongoCloudConnector.java:247)
	at org.mule.module.mongo.processors.InsertObjectMessageProcessor$1.process(InsertObjectMessageProcessor.java:128)
    + 3 more (set debug level logging or '-Dmule.verbose.exceptions=true' for everything)
********************************************************************************
</code>

**Comment by cmartinezledo** [comment]
You are right apt-sky, the record does get inserted into the collection. This issue has been fixed and now, you will only recieve the "_id" value without any ClassCastException.
