### ISSUE TITLE
Exception handling and thrown exceptions are not in line with the other ObjectStore implementations

### ISSUE THREAD

**Issue by simoneavossa** [mulesoft/mongo-connector#47]
It seems that the methods implemented by MongoObjectStore do not throw the expected exceptions according to the other Mule ObjectsStore implementations.

The methods **contains**, **allKeys**, **allPartitions**, **store**, **retrieve**, **remove**, **disposePartition**, **expire** do not catch any exceptions nor wrap the exceptions into ObjectStoreException. This forces to change the implementation of the other classes that wish to use the MongoObjectStore implementation seamlessly.

Specifically, the **store** method should throw ObjectAlreadyExistsException if the key already exists in MongoDB, whereas the **store** method at line 236 uses:

```java
mongoClient.updateObjects(collection, query, dbObject, true, false, getWriteConcern());
```

This is not the expected behaviour based on what is implemented by the other object stores in Mule ESB.

The **store** method should do something like this instead:

```java
try
{
    mongoClient.insertObject(collection, dbObject, getWriteConcern());
}
catch (MongoException.DuplicateKey e)
{
    throw new ObjectAlreadyExistsException();
}
```

**Comment by cmartinezledo** [comment]
A Jira ticket has been created in order to treat this issue. For more information, you can see the ticket status [here](https://www.mulesoft.org/jira/browse/CLDCONNECT-2365)
